import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/About.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout page='about'>
        <div className={styles.main}>
          <h1>About</h1>

          <p>
            Hello! My name is Nabil and I enjoy creating things that live on
            the internet. My interest in web development started back in school when I was playing around with Wordpress — turns out
            hacking together a small site taught me a lot about HTML & CSS!
          </p>

          <p>
            Fast-forward to today, and I’ve had the privilege of working at an
            automotive industry, and a start-up. My main focus these days is building
            accessible, inclusive products and digital experiences.
          </p>

          <p>Here are a few technologies I’ve been working with recently:</p>

          <div className={styles.columns}>
            <div>
              <h4>Frontend</h4>
              <ul>
                <li>Javascript</li>
                <li>Typescript</li>
                <li>Angular</li>
                <li>React</li>
                <li>NextJS</li>
              </ul>
            </div>

            <div>
              <h4>Mobile</h4>
              <ul>
                <li>Ionic Framework</li>
                <li>React Native</li>
                <li>Flutter</li>
              </ul>
            </div>

            <div>
              <h4>Backend</h4>
              <ul>
                <li>Node.js</li>
                <li>PHP</li>
              </ul>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
