import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import styles from '../styles/About.module.scss'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout page="blog">
        
        <div className={styles.main}>
          <h1>Blog</h1>
          <p>Coming soon!</p>
        </div>
        
      </Layout>
    </>
  )
}

export default Home
