import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import styles from "../styles/Contact.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout page="contact">
        <div className={styles.main}>
          <h1>Get In Touch</h1>

          <p>
            My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
          </p>

          <a className={styles.emailLink} href="mailto:nabil@nabilmusa.com" rel="noopener noreferrer" target="_blank">Say Hello</a>

        </div>
      </Layout>
    </>
  );
};

export default Home;
